### ISSUE TITLE
Getting an Unauthenticated Error Message

### ISSUE THREAD

**Issue by VimKanzoGH** [codeofdigital/laravel-url-shortener#2]
Hello @codeofdigital,

Great job with this package and I like the fact that it provides different drivers one can choose from, but I'm having an issue where regardless of the driver I choose, it throws the following response though I set the right credentials for them. I have tried bitly, shorte but none seems to be working for me. I get the same error message for all. The error message is below.

error: "Unauthenticated."
responseCode: 401

Any way out of this?

Thanks

**Comment by VimKanzoGH** [comment]
I just found out that the issue was due to the default driver that was set in the config file. It was set to tiny_url while I was trying to test with bitly. and shorte through my .env file. Again, thanks very much for this great package. I wish we could work on improving it especially in the area of pulling the stats from some of the providers that have them. Let me know what you think?

**Comment by codeofdigital** [comment]
Hi @VimKanzoGH,

Thank you so much for trying out my Laravel package. Indeed there is a lot of improvements can be made and I've had some proposals and ideas to implement short URLs statistics for each drivers used. For sure we can work on it, and in the meantime, you can fork this repo or create a PR on the enhancement that you have suggested and see where we can go from it.
